### ISSUE TITLE
Replace teo.dae with script to generate it

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-openrave-models#32]
Replace `teo.dae` with script to generate it, because we do not even know where it is coming from.

**Comment by jgvictores** [comment]
* Note: I was about to delete it because my OpenRAVE cannot even open it (currently at https://github.com/roboticslab-uc3m/teo-openrave-models/blob/9c8ab84d78b5dcf90e25a7f412011597288818eb/openrave/teo/teo.dae), ~but then I remembered I believe COLLADA can only be open with the OSG viewer plugin (not the Qt one I use)~ EDIT: see https://github.com/roboticslab-uc3m/teo-openrave-models/issues/32#issuecomment-560523758

**Comment by jgvictores** [comment]
Deleted at https://github.com/roboticslab-uc3m/teo-openrave-models/commit/176e7a4e325e953da4d52e1042cdae09c4c409bd

EDIT: LOL I forgot about my above comment, https://github.com/roboticslab-uc3m/teo-openrave-models/issues/32#issuecomment-554129923. Not reverting anyway.

**Comment by jgvictores** [comment]
Turns out this is as easy as:
- <http://openrave.org/docs/0.8.2/robots_overview/>:
```bash
openrave -save myrobot.zae myrobot.xml
```
- <http://openrave-users-list.185357.n3.nabble.com/Creating-COLLADA-file-td4025650.html>:
```
openrave -save myrobot.dae myrobot.xml
```

Note that you may not be able to open the file with OpenRAVE (I believe it must be compiled with OSG). However, I was able to load `openrave -save teo_dextra.robot.dae teo_dextra.robot.xml` on `Gazebo 7` via (well... missing feet for some reason):
```xml
<?xml version="1.0"?>
<sdf version="1.4">
  <world name="default">
    <include>
      <uri>model://ground_plane</uri>
    </include>
    <include>
      <uri>model://sun</uri>
    </include>
    <model name="my_mesh">
      <pose>0 0 1.0  0 0 0</pose>
      <static>true</static>
      <link name="body">
        <visual name="visual">
          <geometry>
            <mesh><uri>file://teo.robot_dextra.dae</uri></mesh>
          </geometry>
        </visual>
      </link>
    </model>
  </world>
</sdf>
```

Note: [ref](https://docs.esko.com/docs/en-us/studiovisualizer/14/userguide/home.html?q=en-us/common/vis/concept/co_export_3d_file.html): Collada is a COLLAborative Design Activity for establishing an interchange file format for interactive 3D applications.
- a Collada file (.dae) contains the 3D geometry of the design, but may link to a number of external artwork files or other .dae files.
- a Collada archive (.zae) file is an archive that contains the original Collada file (.dae), all additional artwork and material files, and additional information.
    - By changing the extension of the .zae file to .zip, you can extract the file and view or use the individual files.

However, `Gazebo 7` crashes on the `.zae`:   `what():  OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource /home/yo/teo_dextra.robot.zae in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreResourceGroupManager.cpp (line 756)` (the `.dae` in the unzipped `.zae` is larger than the original `.dae`).

**Comment by jgvictores** [comment]
Scripts added at https://github.com/roboticslab-uc3m/teo-openrave-models/commit/358ddcc067dec62d0034b5a3b5e27926168651bd

**Comment by jgvictores** [comment]
> Note that you may not be able to open the file with OpenRAVE (I believe it must be compiled with OSG).

Nope. From https://github.com/roboticslab-uc3m/installation-guides/blob/5011b64c0b4512e277d40d49511c64d86dcb8a2c/install-openrave.md#install-openrave-most-modern-ubuntu-such-as-1404-or-1604
```bash
sudo apt install libcollada-dom2.4-dp-dev`  # Open .zae files, only Ubuntu 16.04
```

**Comment by jgvictores** [comment]
Updated info at http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html#generate-databases via https://github.com/roboticslab-uc3m/installation-guides/commit/d925179977b6986a20204e073b6d22b3f8bf2d8d
